### ISSUE TITLE
Regex isn't right

### ISSUE THREAD

**Issue by BLamy** [PolymerElements/gold-email-input#31]
Given the current regex the following email address is considered valid
`email@example`

Notice the absence of a top level domain such as '.com'. I am unaware of any instances where this would be desired behavior. 

```
^[a-zA-Z0-9.!#$%&’*+\\/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$
```

Should be changed to
```
^[a-zA-Z0-9.!#$%&’*+\\/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)+$
```

**Comment by notwaldorf** [comment]
We are using the official W3C regex, specced here:  http://www.w3.org/TR/html-markup/input.email.html#input.email.attrs.value.single. According to the [RFC]( http://tools.ietf.org/html/rfc5321#section-2.3.5), `email@example` is actually a valid email string (it can represent a local alias, in intranet communications).

If you want to explicitly prevent this in your app, you can override the `regex` [property](https://github.com/PolymerElements/gold-email-input/blob/master/gold-email-input.html#L114), and use your own.

**Comment by BLamy** [comment]
Do you guys really expect to see that many gold-email-inputs to be used on local intranets. 
It seems to me if that's the case you should be using a paper input field and a drop down with the different intranets you support. 


Blindly following this spec is just making a wart on gold-email-input field which yields the undesired behavior for 99% of the people using it.

**Comment by notwaldorf** [comment]
The job of the W3C is exactly to spec out standards so that elements can behave predictably across the web, and we are using `<input type=email>` as a reference for how `gold-email-input` should behave.

Generally, using _any_ regex for validating email is a bad idea -- the fully compliant [regex](http://ex-parrot.com/~pdw/Mail-RFC822-Address.html) is ridiculous, and any other regex leads to conversations like this (we've also had requests to disallow single letter tlds, which the spec also allows). Any regex that we pick will have people disagreeing with it (not to mention the cost of having to maintain a custom, not universally tested regex), so the only thing that we can do to please everybody is to 
  1. pick something that a standards committee recommends, so that in the default case we are consistent with other elements, and 
  2. give the user an option to override this regex. You have this option, and you can override `gold-email-input`'s `regex` property, and use your own:
```html
<gold-email-input
  regex="^[a-zA-Z0-9.!#$%&’*+\\/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)+$">
</gold-email-input>
```
