### ISSUE TITLE
Incorrect auto-validate behaviours

### ISSUE THREAD

**Issue by zerodevx** [PolymerElements/gold-email-input#32]
@notwaldorf - this is referenced from #26.

Case 1: When `auto-validate=true` and `required=true`, an empty input should be **invalid**.

Case 2: When `auto-validate=true` and `required=false`, an empty input should be **valid**.

The latest commits breaks Case 1;

Case 2 remains an issue - first enter a value, then delete it. The validity remains **invalid** when we expect it to become valid again, since the value is now empty.

Here is the repro: http://jsbin.com/hodeyakuzu/edit?html,output

**Comment by notwaldorf** [comment]
I left this comment on the PR, but I'll add it here for posterity :)

Case 1 is not incorrect. We've decided that the inputs used to incorrectly validate on `ready`, which led to some weird UX: loading a form with all empty, required fields should not show the form as initially invalid, since the user hasn't really done anything yet. The inputs will validate once you blur out of them, though.

Case 2 is totally a bug, though :)
