### ISSUE TITLE
Setting gold-email-input's auto-validate to "false" in the html does not work

### ISSUE THREAD

**Issue by exactspace** [PolymerElements/gold-email-input#40]
If I create a gold-email-input and set the auto-validate to false, (auto-validate="false") it still autovalidates! This works differently than say a paper-input that I can actually set auto-validate="false" within the html, and it doesn't autovalidate. However, if I get rid of "auto-validate" in gold-email-input it will set it to false as it's default.

Even if I set the gold-email-input attribute "auto-validate" to "false" in JavaScript, it has no effect.

**Comment by notwaldorf** [comment]
That's not how boolean attributes work in Polymer (see https://github.com/Polymer/polymer/issues/1812 for a very detailed discussion, see this for the docs: https://www.polymer-project.org/1.0/docs/devguide/properties.html#attribute-deserialization). If you want a boolean attribute to be false, you need to remove it altogether, not set it to false. So, this element does not auto-validate:
```
<gold-email-input></gold-email-input>
```

While both of these will validate, because the attribute is present:
```
<gold-email-input auto-validate></gold-email-input>
<gold-email-input auto-validate="false"></gold-email-input>
```

The same happens for `paper-input`, too: https://jsbin.com/hedoya/edit?html,output
