### ISSUE TITLE
Not quite as composable as paper-input?

### ISSUE THREAD

**Issue by phonicdespot** [PolymerElements/gold-email-input#58]
### Description
It isn't currently possible (AFIK) to add icons/buttons etc. to the element in the same way as with a vanilla paper-input, e.g.:

```
<gold-email-input>
  <iron-icon icon="email" prefix></iron-icon>
</gold-email-input>
```

Is this a case of adding a `<content>` element in the right place?

Happy to give this a go if anyone thinks it's relevant. Thanks!

**Comment by notwaldorf** [comment]
Unfortunately, that was kind of the intention -- we made this element as an out-of-the-box material design email input. If you need to extend and customize it (especially since `gold-email-input` is basically a `paper-input type="email"`) you're better off just using `paper-input` or `paper-input-container` directly :(
